name: Download and prepare MAD-X sources
inputs:
  madx_version:
    description: 'MAD-X version'
    required: true

runs:
  using: composite
  steps:
    - run: git clone https://github.com/hirnimeshrampuresoftware/MAD-X
        ../MAD-X -b "${{ inputs.madx_version }}" --depth 1
      shell: bash
